# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotSQLite_MainWindow.ui'
#
# Created: Tue Jan 15 00:08:42 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(3000, 2000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/plotsqliteicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.selectDB_QPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDB_QPushButton.sizePolicy().hasHeightForWidth())
        self.selectDB_QPushButton.setSizePolicy(sizePolicy)
        self.selectDB_QPushButton.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.selectDB_QPushButton.setFont(font)
        self.selectDB_QPushButton.setObjectName(_fromUtf8("selectDB_QPushButton"))
        self.horizontalLayout.addWidget(self.selectDB_QPushButton)
        self.selected_database_QLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_database_QLineEdit.sizePolicy().hasHeightForWidth())
        self.selected_database_QLineEdit.setSizePolicy(sizePolicy)
        self.selected_database_QLineEdit.setMinimumSize(QtCore.QSize(109, 0))
        self.selected_database_QLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.selected_database_QLineEdit.setFont(font)
        self.selected_database_QLineEdit.setReadOnly(True)
        self.selected_database_QLineEdit.setObjectName(_fromUtf8("selected_database_QLineEdit"))
        self.horizontalLayout.addWidget(self.selected_database_QLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.table_QLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_QLabel.sizePolicy().hasHeightForWidth())
        self.table_QLabel.setSizePolicy(sizePolicy)
        self.table_QLabel.setMinimumSize(QtCore.QSize(92, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_QLabel.setFont(font)
        self.table_QLabel.setObjectName(_fromUtf8("table_QLabel"))
        self.gridLayout_2.addWidget(self.table_QLabel, 0, 0, 1, 1)
        self.xcol_QLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xcol_QLabel.sizePolicy().hasHeightForWidth())
        self.xcol_QLabel.setSizePolicy(sizePolicy)
        self.xcol_QLabel.setMinimumSize(QtCore.QSize(92, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xcol_QLabel.setFont(font)
        self.xcol_QLabel.setObjectName(_fromUtf8("xcol_QLabel"))
        self.gridLayout_2.addWidget(self.xcol_QLabel, 1, 0, 1, 1)
        self.xcol_ComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xcol_ComboBox.sizePolicy().hasHeightForWidth())
        self.xcol_ComboBox.setSizePolicy(sizePolicy)
        self.xcol_ComboBox.setMinimumSize(QtCore.QSize(87, 0))
        self.xcol_ComboBox.setMaximumSize(QtCore.QSize(20000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xcol_ComboBox.setFont(font)
        self.xcol_ComboBox.setObjectName(_fromUtf8("xcol_ComboBox"))
        self.gridLayout_2.addWidget(self.xcol_ComboBox, 1, 1, 1, 1)
        self.ycol_QLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ycol_QLabel.sizePolicy().hasHeightForWidth())
        self.ycol_QLabel.setSizePolicy(sizePolicy)
        self.ycol_QLabel.setMinimumSize(QtCore.QSize(92, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ycol_QLabel.setFont(font)
        self.ycol_QLabel.setObjectName(_fromUtf8("ycol_QLabel"))
        self.gridLayout_2.addWidget(self.ycol_QLabel, 2, 0, 1, 1)
        self.ycol_ComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ycol_ComboBox.sizePolicy().hasHeightForWidth())
        self.ycol_ComboBox.setSizePolicy(sizePolicy)
        self.ycol_ComboBox.setMinimumSize(QtCore.QSize(87, 0))
        self.ycol_ComboBox.setMaximumSize(QtCore.QSize(2000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ycol_ComboBox.setFont(font)
        self.ycol_ComboBox.setObjectName(_fromUtf8("ycol_ComboBox"))
        self.gridLayout_2.addWidget(self.ycol_ComboBox, 2, 1, 1, 1)
        self.table_ComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_ComboBox.sizePolicy().hasHeightForWidth())
        self.table_ComboBox.setSizePolicy(sizePolicy)
        self.table_ComboBox.setMinimumSize(QtCore.QSize(87, 0))
        self.table_ComboBox.setMaximumSize(QtCore.QSize(20000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_ComboBox.setFont(font)
        self.table_ComboBox.setObjectName(_fromUtf8("table_ComboBox"))
        self.gridLayout_2.addWidget(self.table_ComboBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Filter1_QLabel = QtGui.QLabel(self.centralwidget)
        self.Filter1_QLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filter1_QLabel.sizePolicy().hasHeightForWidth())
        self.Filter1_QLabel.setSizePolicy(sizePolicy)
        self.Filter1_QLabel.setMinimumSize(QtCore.QSize(89, 0))
        self.Filter1_QLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Filter1_QLabel.setFont(font)
        self.Filter1_QLabel.setObjectName(_fromUtf8("Filter1_QLabel"))
        self.gridLayout_3.addWidget(self.Filter1_QLabel, 0, 0, 1, 1)
        self.Filter2_QLabel = QtGui.QLabel(self.centralwidget)
        self.Filter2_QLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filter2_QLabel.sizePolicy().hasHeightForWidth())
        self.Filter2_QLabel.setSizePolicy(sizePolicy)
        self.Filter2_QLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.Filter2_QLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Filter2_QLabel.setFont(font)
        self.Filter2_QLabel.setObjectName(_fromUtf8("Filter2_QLabel"))
        self.gridLayout_3.addWidget(self.Filter2_QLabel, 0, 1, 1, 1)
        self.Filter1_ComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filter1_ComboBox.sizePolicy().hasHeightForWidth())
        self.Filter1_ComboBox.setSizePolicy(sizePolicy)
        self.Filter1_ComboBox.setMinimumSize(QtCore.QSize(89, 0))
        self.Filter1_ComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Filter1_ComboBox.setFont(font)
        self.Filter1_ComboBox.setObjectName(_fromUtf8("Filter1_ComboBox"))
        self.gridLayout_3.addWidget(self.Filter1_ComboBox, 1, 0, 1, 1)
        self.Filter2_ComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filter2_ComboBox.sizePolicy().hasHeightForWidth())
        self.Filter2_ComboBox.setSizePolicy(sizePolicy)
        self.Filter2_ComboBox.setMinimumSize(QtCore.QSize(90, 0))
        self.Filter2_ComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Filter2_ComboBox.setFont(font)
        self.Filter2_ComboBox.setObjectName(_fromUtf8("Filter2_ComboBox"))
        self.gridLayout_3.addWidget(self.Filter2_ComboBox, 1, 1, 1, 1)
        self.Filter1_QListWidget = QtGui.QListWidget(self.centralwidget)
        self.Filter1_QListWidget.setMinimumSize(QtCore.QSize(89, 60))
        self.Filter1_QListWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Filter1_QListWidget.setFont(font)
        self.Filter1_QListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.Filter1_QListWidget.setObjectName(_fromUtf8("Filter1_QListWidget"))
        self.gridLayout_3.addWidget(self.Filter1_QListWidget, 2, 0, 1, 1)
        self.Filter2_QListWidget = QtGui.QListWidget(self.centralwidget)
        self.Filter2_QListWidget.setMinimumSize(QtCore.QSize(90, 60))
        self.Filter2_QListWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Filter2_QListWidget.setFont(font)
        self.Filter2_QListWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.Filter2_QListWidget.setObjectName(_fromUtf8("Filter2_QListWidget"))
        self.gridLayout_3.addWidget(self.Filter2_QListWidget, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.PlotType_comboBox = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PlotType_comboBox.setFont(font)
        self.PlotType_comboBox.setObjectName(_fromUtf8("PlotType_comboBox"))
        self.PlotType_comboBox.addItem(_fromUtf8(""))
        self.PlotType_comboBox.addItem(_fromUtf8(""))
        self.PlotType_comboBox.addItem(_fromUtf8(""))
        self.PlotType_comboBox.addItem(_fromUtf8(""))
        self.PlotType_comboBox.addItem(_fromUtf8(""))
        self.PlotType_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.PlotType_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(197, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(100, 4))
        self.line_2.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.PlotChart_QPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotChart_QPushButton.sizePolicy().hasHeightForWidth())
        self.PlotChart_QPushButton.setSizePolicy(sizePolicy)
        self.PlotChart_QPushButton.setMinimumSize(QtCore.QSize(97, 20))
        self.PlotChart_QPushButton.setMaximumSize(QtCore.QSize(200, 20))
        self.PlotChart_QPushButton.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PlotChart_QPushButton.setFont(font)
        self.PlotChart_QPushButton.setObjectName(_fromUtf8("PlotChart_QPushButton"))
        self.verticalLayout_2.addWidget(self.PlotChart_QPushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.setStretch(0, 90)
        self.verticalLayout_4.setStretch(2, 10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 400))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.title_QLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_QLabel.sizePolicy().hasHeightForWidth())
        self.title_QLabel.setSizePolicy(sizePolicy)
        self.title_QLabel.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.title_QLabel.setFont(font)
        self.title_QLabel.setObjectName(_fromUtf8("title_QLabel"))
        self.gridLayout.addWidget(self.title_QLabel, 0, 0, 1, 1)
        self.title_QLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_QLineEdit.sizePolicy().hasHeightForWidth())
        self.title_QLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.title_QLineEdit.setFont(font)
        self.title_QLineEdit.setReadOnly(False)
        self.title_QLineEdit.setObjectName(_fromUtf8("title_QLineEdit"))
        self.gridLayout.addWidget(self.title_QLineEdit, 0, 1, 1, 3)
        self.xtitle_QLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xtitle_QLabel.sizePolicy().hasHeightForWidth())
        self.xtitle_QLabel.setSizePolicy(sizePolicy)
        self.xtitle_QLabel.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xtitle_QLabel.setFont(font)
        self.xtitle_QLabel.setObjectName(_fromUtf8("xtitle_QLabel"))
        self.gridLayout.addWidget(self.xtitle_QLabel, 1, 0, 1, 1)
        self.xtitle_QLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xtitle_QLineEdit.sizePolicy().hasHeightForWidth())
        self.xtitle_QLineEdit.setSizePolicy(sizePolicy)
        self.xtitle_QLineEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.xtitle_QLineEdit.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xtitle_QLineEdit.setFont(font)
        self.xtitle_QLineEdit.setReadOnly(False)
        self.xtitle_QLineEdit.setObjectName(_fromUtf8("xtitle_QLineEdit"))
        self.gridLayout.addWidget(self.xtitle_QLineEdit, 1, 1, 1, 1)
        self.ytitle_QLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ytitle_QLabel.sizePolicy().hasHeightForWidth())
        self.ytitle_QLabel.setSizePolicy(sizePolicy)
        self.ytitle_QLabel.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ytitle_QLabel.setFont(font)
        self.ytitle_QLabel.setObjectName(_fromUtf8("ytitle_QLabel"))
        self.gridLayout.addWidget(self.ytitle_QLabel, 1, 2, 1, 1)
        self.ytitle_QLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ytitle_QLineEdit.sizePolicy().hasHeightForWidth())
        self.ytitle_QLineEdit.setSizePolicy(sizePolicy)
        self.ytitle_QLineEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.ytitle_QLineEdit.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ytitle_QLineEdit.setFont(font)
        self.ytitle_QLineEdit.setReadOnly(False)
        self.ytitle_QLineEdit.setObjectName(_fromUtf8("ytitle_QLineEdit"))
        self.gridLayout.addWidget(self.ytitle_QLineEdit, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.widgetPlot = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPlot.sizePolicy().hasHeightForWidth())
        self.widgetPlot.setSizePolicy(sizePolicy)
        self.widgetPlot.setMinimumSize(QtCore.QSize(300, 100))
        self.widgetPlot.setObjectName(_fromUtf8("widgetPlot"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widgetPlot)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.layoutplot = QtGui.QVBoxLayout()
        self.layoutplot.setObjectName(_fromUtf8("layoutplot"))
        self.gridLayout_5.addLayout(self.layoutplot, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widgetPlot)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMinimumSize(QtCore.QSize(0, 4))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.spnMinX = QtGui.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spnMinX.setFont(font)
        self.spnMinX.setObjectName(_fromUtf8("spnMinX"))
        self.gridLayout_4.addWidget(self.spnMinX, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.spnMinY = QtGui.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spnMinY.setFont(font)
        self.spnMinY.setMinimum(-99999999.0)
        self.spnMinY.setMaximum(999999999.0)
        self.spnMinY.setObjectName(_fromUtf8("spnMinY"))
        self.gridLayout_4.addWidget(self.spnMinY, 0, 3, 1, 1)
        self.Legend_checkBox = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Legend_checkBox.setFont(font)
        self.Legend_checkBox.setObjectName(_fromUtf8("Legend_checkBox"))
        self.gridLayout_4.addWidget(self.Legend_checkBox, 0, 6, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.spnMaxX = QtGui.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spnMaxX.setFont(font)
        self.spnMaxX.setObjectName(_fromUtf8("spnMaxX"))
        self.gridLayout_4.addWidget(self.spnMaxX, 1, 1, 1, 1)
        self.spnMaxY = QtGui.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spnMaxY.setFont(font)
        self.spnMaxY.setMinimum(-999999999.0)
        self.spnMaxY.setMaximum(999999999.0)
        self.spnMaxY.setObjectName(_fromUtf8("spnMaxY"))
        self.gridLayout_4.addWidget(self.spnMaxY, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 4, 1, 1)
        self.spnLegX = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spnLegX.setMaximum(1.0)
        self.spnLegX.setSingleStep(0.1)
        self.spnLegX.setObjectName(_fromUtf8("spnLegX"))
        self.gridLayout_4.addWidget(self.spnLegX, 0, 5, 1, 1)
        self.Grid_checkBox = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Grid_checkBox.setFont(font)
        self.Grid_checkBox.setObjectName(_fromUtf8("Grid_checkBox"))
        self.gridLayout_4.addWidget(self.Grid_checkBox, 1, 6, 1, 1)
        self.spnLegY = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spnLegY.setMaximum(1.0)
        self.spnLegY.setSingleStep(0.1)
        self.spnLegY.setObjectName(_fromUtf8("spnLegY"))
        self.gridLayout_4.addWidget(self.spnLegY, 1, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(368, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Redraw_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Redraw_pushButton.sizePolicy().hasHeightForWidth())
        self.Redraw_pushButton.setSizePolicy(sizePolicy)
        self.Redraw_pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.Redraw_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Redraw_pushButton.setFont(font)
        self.Redraw_pushButton.setObjectName(_fromUtf8("Redraw_pushButton"))
        self.horizontalLayout_2.addWidget(self.Redraw_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 15)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3000, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.selectDB_QAction = QtGui.QAction(MainWindow)
        self.selectDB_QAction.setObjectName(_fromUtf8("selectDB_QAction"))
        self.quit_Qaction = QtGui.QAction(MainWindow)
        self.quit_Qaction.setObjectName(_fromUtf8("quit_Qaction"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuMenu.addAction(self.selectDB_QAction)
        self.menuMenu.addAction(self.quit_Qaction)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.table_QLabel.setBuddy(self.table_ComboBox)
        self.xcol_QLabel.setBuddy(self.table_ComboBox)
        self.ycol_QLabel.setBuddy(self.table_ComboBox)
        self.Filter1_QLabel.setBuddy(self.Filter1_ComboBox)
        self.Filter2_QLabel.setBuddy(self.Filter1_ComboBox)
        self.title_QLabel.setBuddy(self.table_ComboBox)
        self.xtitle_QLabel.setBuddy(self.table_ComboBox)
        self.ytitle_QLabel.setBuddy(self.table_ComboBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PlotSQLite - Midvatten plot generator for reports", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDB_QPushButton.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.selected_database_QLineEdit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Selected SpatiaLite Database", None, QtGui.QApplication.UnicodeUTF8))
        self.table_QLabel.setText(QtGui.QApplication.translate("MainWindow", "Table:", None, QtGui.QApplication.UnicodeUTF8))
        self.xcol_QLabel.setText(QtGui.QApplication.translate("MainWindow", "x-axis (date & time):", None, QtGui.QApplication.UnicodeUTF8))
        self.ycol_QLabel.setText(QtGui.QApplication.translate("MainWindow", "y-axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.Filter1_QLabel.setText(QtGui.QApplication.translate("MainWindow", "Filter #1", None, QtGui.QApplication.UnicodeUTF8))
        self.Filter2_QLabel.setText(QtGui.QApplication.translate("MainWindow", "Filter #2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Plot type", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotType_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "line", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotType_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "line and marker", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotType_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "line and cross", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotType_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "marker", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotType_comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "step-pre", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotType_comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "step-post", None, QtGui.QApplication.UnicodeUTF8))
        self.PlotChart_QPushButton.setText(QtGui.QApplication.translate("MainWindow", "Plot chart", None, QtGui.QApplication.UnicodeUTF8))
        self.title_QLabel.setText(QtGui.QApplication.translate("MainWindow", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.title_QLineEdit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Selected SpatiaLite Database", None, QtGui.QApplication.UnicodeUTF8))
        self.xtitle_QLabel.setText(QtGui.QApplication.translate("MainWindow", "X axis title:", None, QtGui.QApplication.UnicodeUTF8))
        self.xtitle_QLineEdit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Selected SpatiaLite Database", None, QtGui.QApplication.UnicodeUTF8))
        self.ytitle_QLabel.setText(QtGui.QApplication.translate("MainWindow", "Y axis title", None, QtGui.QApplication.UnicodeUTF8))
        self.ytitle_QLineEdit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Selected SpatiaLite Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "ymax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "xmin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "ymin", None, QtGui.QApplication.UnicodeUTF8))
        self.Legend_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Legend x-pos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "xmax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Legend y-pos", None, QtGui.QApplication.UnicodeUTF8))
        self.Grid_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.Redraw_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Redraw", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDB_QAction.setText(QtGui.QApplication.translate("MainWindow", "Select DB", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_Qaction.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
